# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: 7Zo%3zXCN328KXBZUw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: XaDuL96P)8vz84vzLF
    salt: "FHRtLxwg6w3964GE>j"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  foodiesandthebeast.com:
    env:
      db_password: 43ve97if&QbDR6PzKs
      # Generate your keys here: https://roots.io/salts.html
auth_key: "5Cg-`v%MyG<mR?db#!:K4-a!lck}*nQ}1:v}vK.(a$_Kygmr{W1NR@&zMRQk^$9O"
secure_auth_key: "?PP<-U$(<zg.f;M1AX3$i;[nJ$3VbX]%e,W1DioVo10jnW|>x!nzaX]G4L%haa!J"
logged_in_key: "[2_=w]f,lh-sh.*+3%$DjN%bJErm(rkYj&>y&T;18y%$6%hq[tu*kiu_Xh)9a,RS"
nonce_key: "c]mAqs3E*Qv-oRU}m9y;Tt5!Kj3*EhSK{@$?CP,w]fI$lIXTV-Rlo`}z3EYdisjf"
auth_salt: "Fbo&sxM|{G&`Nzxu|L>hMl,@@V#yHs$AVY}v#%=wMl,Hj)p7,Dv;%0R+26v$O5h+"
secure_auth_salt: "^BZR</``Ple4(BzkD&gtXr.q=:Uv/Ws*2&2V[L&tlgBhnF:MY%g@DiNrU0MtAPKO"
logged_in_salt: "aq;aZz1SucdAvZ.1!V!k[p/(!QNfE]xtLk+ne(N?sQlqdg$&vv5HI,Z(OS[D),-4"
nonce_salt: "|a*!IaaJafY2S(Hb*n2TDbi9NBU8;D)@?[RcKIC%DI-t7:hCl)sdd8GycqQ83m:w"
